src/Pride2/Models/Dealers/City.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Pride2.Models.Dealers
{
    public class City
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual Region Region { get; set; }
        public virtual List<Shop> Shops { get; set; }
    }
}

src/Pride2/Models/Dealers/Dealer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Pride2.Models.Dealers
{
    public class Dealer
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public string Surname { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        public virtual List<Shop> Shops { get; set; }

    }
}

src/Pride2/Models/Dealers/Phone.cs
using System.ComponentModel.DataAnnotations;

namespace Pride2.Models.Dealers
{
    public class Phone
    {
        public int Id { get; set; }

        [Required]
        public string PhoneNumber { get; set; }

        public Shop Shop { get; set; }
    }
}

src/Pride2/Models/Dealers/Region.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Pride2.Models.Dealers
{
    public class Region
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual List<City> Cities { get; set; }
    }
}

src/Pride2/Models/Dealers/Shop.cs
using System.Collections.Generic;

namespace Pride2.Models.Dealers
{
    public class Shop
    {
        public int Id { get; set; }

        public string Name { get; set; }
        public string Address { get; set; }
        public string WorkingTime { get; set; }
        public string CoordX { get; set; }
        public string CoordY { get; set; }

        public virtual Dealer Dealer { get; set; }
        public virtual City City { get; set; }
        public virtual List<Phone> Phones { get; set; }
    }
}

src/Pride2/Areas/Admin/Controllers/Dealers/CityController.cs
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Pride2.Areas.Admin.ViewModels;
using Pride2.Models;
using Pride2.Models.Dealers;

namespace Pride2.Areas.Admin.Controllers.Dealers
{
    [Area("admin")]
    [Route("admin/dealers/city")]
    public class CityController : Controller
    {
        private ApplicationDbContext _context;

        public CityController(ApplicationDbContext context)
        {
            _context = context;    
        }

        [Route("create")]
        public async Task<IActionResult> Create(int? regionId)
        {
            if (regionId != null)
            {
                var region = await _context.ContactsRegions.SingleOrDefaultAsync(x => x.Id == regionId);

                if (region != null)
                {
                    CityEditViewModel model = new CityEditViewModel()
                    {
                        City = new City(),
                        RegionId = region.Id
                    };

                    return View("Edit", model);
                }
            }

            return HttpNotFound();
        }

        [Route("edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            City city = await _context.ContactsCities.Include(x => x.Region).SingleAsync(x => x.Id == id);

            if (city != null)
            {
                CityEditViewModel model = new CityEditViewModel()
                {
                    City = city,
                    RegionId = city.Region.Id
                };

                return View(model);
            }

            return HttpNotFound();
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit(CityEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.City.Region = await _context.ContactsRegions.SingleOrDefaultAsync(x => x.Id == model.RegionId);

                if (model.City.Region == null)
                {
                    return HttpNotFound();
                }

                if (model.City.Id == 0)
                {
                    _context.Entry(model.City).State = EntityState.Added;

                    TempData["Message"] = $"City: {model.City.Name} create!";
                }
                else
                {
                    _context.Entry(model.City).State = EntityState.Modified;

                    TempData["Message"] = $"City: {model.City.Name} save!";
                }

                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Regions");
            }

            return View(model);
        }

        [HttpPost("delete")]
        public async Task<IActionResult> Delete(int id)
        {
            City city = await _context.ContactsCities.SingleAsync(x => x.Id == id);

            if (city != null)
            {
                _context.ContactsCities.Remove(city);

                TempData["Message"] = $"City: {city.Name} delete!";
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Regions");
        }
    }
}

src/Pride2/Areas/Admin/Controllers/Dealers/DealerController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.ChangeTracking;
using Pride2.Models;
using Pride2.Models.Dealers;

namespace Pride2.Areas.Admin.Controllers.Dealers
{
    [Area("admin")]
    [Route("admin/dealers")]
    public class DealerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DealerController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            var dialerList = await _context.Dealers.Include(x => x.Shops).ThenInclude(x => x.City).ToListAsync();

            return View(dialerList);
        }

        [Route("create")]
        public IActionResult Create()
        {
            var dealer = new Dealer();

            return View(nameof(Edit), dealer);
        }

        [HttpGet("edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Dealer dealer = await _context.Dealers.SingleAsync(x => x.Id == id);

            if (dealer != null)
            {
                return View(dealer);
            }

            return HttpNotFound();
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit(Dealer dealer)
        {
            if (ModelState.IsValid)
            {

                if (dealer.Id == 0)
                {
                    _context.Entry(dealer).State = EntityState.Added;

                    TempData["Message"] = $"Dealer: {dealer.Name} {dealer.Surname} create!";
                }
                else
                {
                    _context.Entry(dealer).State = EntityState.Modified;

                    TempData["Message"] = $"Dealer: {dealer.Name} {dealer.Surname} save!";
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(dealer);
        }

        [HttpPost("delete")]
        public async Task<IActionResult> Delete(int id)
        {
            Dealer dealer = await _context.Dealers.Include(x => x.Shops).SingleAsync(x => x.Id == id);

            if (dealer != null)
            {
                _context.Dealers.Remove(dealer);

                await _context.SaveChangesAsync();

                TempData["Message"] = $"Dealer: {dealer.Name} {dealer.Surname} delete!";
            }
            else
            {
                TempData["ErrorMessage"] = "Dealer not found!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

src/Pride2/Areas/Admin/Controllers/Dealers/RegionsController.cs
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Pride2.Models;
using Pride2.Models.Dealers;

namespace Pride2.Areas.Admin.Controllers.Dealers
{
    [Area("admin")]
    [Route("admin/dealers/regions")]
    public class RegionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RegionsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ContactsRegions.Include(x => x.Cities).ToListAsync());
        }

        [Route("create")]
        public IActionResult Create()
        {
            return View("Edit", new Region());
        }

        [Route("edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Region region = await _context.ContactsRegions.SingleAsync(m => m.Id == id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit(Region region)
        {
            if (ModelState.IsValid)
            {

                if (region.Id == 0)
                {
                    _context.Entry(region).State = EntityState.Added;

                    TempData["Message"] = $"Region: {region.Name} create!";
                }
                else
                {
                    _context.Entry(region).State = EntityState.Modified;

                    TempData["Message"] = $"Region: {region.Name} save!";
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(region);
        }

        [HttpPost("delete")]
        public async Task<IActionResult> Delete(int id)
        {
            Region region = await _context.ContactsRegions.Include(x => x.Cities).SingleAsync(m => m.Id == id);
            _context.ContactsCities.RemoveRange(region.Cities);
            _context.ContactsRegions.Remove(region);
            await _context.SaveChangesAsync();

            TempData["Message"] = $"Region: {region.Name} delete!";

            return RedirectToAction("Index");
        }
    }
}

src/Pride2/Areas/Admin/Controllers/Dealers/ShopsController.cs
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Pride2.Areas.Admin.ViewModels;
using Pride2.Models;
using Pride2.Models.Dealers;

namespace Pride2.Areas.Admin.Controllers.Dealers
{
    [Area("admin")]
    [Route("admin/dealers/shop")]
    public class ShopsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShopsController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("create")]
        public async Task<IActionResult> Create(int? dealerId)
        {
            if (dealerId != null)
            {
                var dealer = await _context.Dealers.SingleAsync(x => x.Id == dealerId);

                if (dealer != null)
                {
                    ShopEditViewModel model = new ShopEditViewModel()
                    {
                        Shop = new Shop(),
                        Cities = await _context.ContactsCities.ToListAsync(),
                        DealerId = dealer.Id
                    };

                    return View("Edit" , model);
                }
            }

            return HttpNotFound();
        }

        [Route("edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Shop shop = await _context.Shops.Include(x => x.Dealer).SingleAsync(x => x.Id == id);

            if (shop != null)
            {
                ShopEditViewModel model = new ShopEditViewModel()
                {
                    Shop = shop,
                    Cities = await _context.ContactsCities.ToListAsync(),
                    DealerId = shop.Dealer.Id
                };

                return View(model);
            }

            return HttpNotFound();
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit(ShopEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Shop.City = await _context.ContactsCities.SingleAsync(x => x.Id == model.CityId);
                model.Shop.Dealer = await _context.Dealers.SingleAsync(x => x.Id == model.DealerId);

                if (model.Shop.City == null || model.Shop.Dealer == null)
                {
                    return HttpNotFound();
                }

                if (model.Shop.Id == 0)
                {
                    _context.Entry(model.Shop).State = EntityState.Added;

                    TempData["Message"] = $"Shop: {model.Shop.Name} create!";
                }
                else
                {
                    _context.Entry(model.Shop).State = EntityState.Modified;

                    TempData["Message"] = $"Shop: {model.Shop.Name} save!";
                }

                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Dealer");
            }

            return View(model);
        }

        [HttpPost("delete")]
        public async Task<IActionResult> Delete(int id)
        {
            Shop shop = await _context.Shops.SingleAsync(x => x.Id == id);

            if (shop != null)
            {
                _context.Shops.Remove(shop);

                TempData["Message"] = $"Shop: {shop.Name} delete!";
            }

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "Dealer");
        }
    }
}

src/Pride2/Areas/Admin/Views/Dealer/Edit.cshtml
@model Pride2.Models.Dealers.Dealer

@{
    ViewData["Title"] = "Shop Edit";
    ViewData["Menu"] = "Dealer";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card-box">
            <div class="row">
                <div class="col-md-12">
                    <form class="form-horizontal" role="form" asp-controller="Dealer" asp-action="Edit" method="post">
                        <input type="hidden" asp-for="Id" />

                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-2 control-label" asp-for="Name"></label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" asp-for="Name">
                                    <span class="error" asp-validation-for="Name"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-2 control-label" asp-for="Surname"></label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" asp-for="Surname">
                                    <span class="error" asp-validation-for="Surname"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-2 control-label" asp-for="Email"></label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" asp-for="Email">
                                    <span class="error" asp-validation-for="Email"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-right m-b-0">
                            <button type="submit" class="btn btn-default">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Pride2/Areas/Admin/Views/Dealer/Index.cshtml
@model List<Pride2.Models.Dealers.Dealer>
@{
    ViewData["Title"] = "Dealers";
    ViewData["Description"] = "List dealers!";
    ViewData["Menu"] = "Dealer";
}

<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading p-t-15 p-b-15">
                <a class="btn btn-primary waves-effect waves-light w-sm" asp-controller="Dealer" asp-action="Create">
                    <span class="btn-label">
                        <i class="ion-plus-round"></i>
                    </span>
                    Add dealer
                </a>
                <a class="btn btn-success waves-effect waves-light w-sm m-l-10" asp-controller="Regions" asp-action="Index">
                    Regions
                </a>
            </div>
        </div>
    </div>
</div>

@foreach (var dealer in Model)
{
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-right">
                        <a asp-controller="Dealer" asp-action="Edit" asp-route-id="@dealer.Id" type="button" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                            <i class="ion-edit"></i>
                        </a>
                        <form asp-controller="Dealer" asp-action="Delete" method="post" style="display: inline-block" class="m-l-10">
                            <input type="hidden" value="@dealer.Id" name="id" />
                            <button type="submit" class="btn btn-danger waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete">
                                <i class="ion-trash-b"></i>
                            </button>
                        </form>
                    </div>
                    <h4 class="header-title m-t-0">
                        @($"{dealer.Name} {dealer.Surname}")
                    </h4>
                    <p class="text-muted m-b-10 font-13">
                        <a href="mailto:@dealer.Email">@dealer.Email</a>
                    </p>

                    @if (dealer.Shops.Count > 0)
                    {
                        <hr />
                        <h4 class="header-title">Shops:</h4>

                        <div class="bootstrap-table">
                            <table class="table-bordered  table table-hover" style="display: table;">
                                <thead>
                                    <tr>
                                        <th>
                                            <div class="th-inner ">Name</div>
                                            <div class="fht-cell"></div>
                                        </th>
                                        <th>
                                            <div class="th-inner ">City</div>
                                            <div class="fht-cell"></div>
                                        </th>
                                        <th>
                                            <div class="th-inner ">Address</div>
                                            <div class="fht-cell"></div>
                                        </th>
                                        <th>
                                            <div class="th-inner ">Action</div>
                                            <div class="fht-cell"></div>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var shop in dealer.Shops)
                                    {
                                        <tr>
                                            <td style="">@shop.Name</td>
                                            <td style="">@shop.City.Name</td>
                                            <td style="">@shop.Address</td>
                                            <td style="width: 110px;">
                                                <a asp-controller="Shops" asp-action="Edit" asp-route-id="@shop.Id" type="button" class="btn btn-success waves-effect waves-light btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                                                    <i class="ion-edit"></i>
                                                </a>
                                                <form asp-controller="Shops" asp-action="Delete" method="post" style="display: inline-block" class="m-l-10">
                                                    <input type="hidden" value="@shop.Id" name="id" />
                                                    <button type="submit" class="btn btn-danger waves-effect waves-light btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete">
                                                        <i class="ion-trash-b"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    }

                </div>

                <div class="panel-footer p-t-15 p-b-15">
                    <a asp-controller="Shops" asp-action="Create" asp-route-dealerId="@dealer.Id" class="btn btn-primary waves-effect waves-light w-sm">
                        <span class="btn-label">
                            <i class="ion-plus-round"></i>
                        </span>
                        Add shop
                    </a>
                </div>

            </div>
        </div>
    </div>
}