src/Pride2/Models/Dealers/Region.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Pride2.Models.Dealers
{
    public class Region
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual List<City> Cities { get; set; }
    }
}

src/Pride2/Areas/Admin/Controllers/Dealers/RegionsController.cs
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Pride2.Models;
using Pride2.Models.Dealers;

namespace Pride2.Areas.Admin.Controllers.Dealers
{
    [Area("admin")]
    [Route("admin/dealers/regions")]
    public class RegionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RegionsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ContactsRegions.Include(x => x.Cities).ToListAsync());
        }

        [Route("create")]
        public IActionResult Create()
        {
            return View("Edit", new Region());
        }

        [Route("edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Region region = await _context.ContactsRegions.SingleAsync(m => m.Id == id);
            if (region == null)
            {
                return HttpNotFound();
            }
            return View(region);
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit(Region region)
        {
            if (ModelState.IsValid)
            {

                if (region.Id == 0)
                {
                    _context.Entry(region).State = EntityState.Added;

                    TempData["Message"] = $"Region: {region.Name} create!";
                }
                else
                {
                    _context.Entry(region).State = EntityState.Modified;

                    TempData["Message"] = $"Region: {region.Name} save!";
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(region);
        }

        [HttpPost("delete")]
        public async Task<IActionResult> Delete(int id)
        {
            Region region = await _context.ContactsRegions.Include(x => x.Cities).SingleAsync(m => m.Id == id);
            _context.ContactsCities.RemoveRange(region.Cities);
            _context.ContactsRegions.Remove(region);
            await _context.SaveChangesAsync();

            TempData["Message"] = $"Region: {region.Name} delete!";

            return RedirectToAction("Index");
        }
    }
}

src/Pride2/Areas/Admin/Views/Regions/Edit.cshtml
@model Pride2.Models.Dealers.Region

@{
    ViewData["Title"] = "Region edit";
    ViewData["Menu"] = "Dealer";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card-box">
            <div class="row">
                <div class="col-md-12">
                    <form class="form-horizontal" role="form" asp-controller="Regions" asp-action="Edit" method="post">
                        <input type="hidden" asp-for="Id" />

                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-2 control-label" asp-for="Name"></label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" asp-for="Name">
                                    <span class="error" asp-validation-for="Name"></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-right m-b-0">
                            <button type="submit" class="btn btn-default">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/Pride2/Areas/Admin/Views/Regions/Index.cshtml
@model List<Pride2.Models.Dealers.Region>

@{
    ViewData["Title"] = "Regions";
    ViewData["Description"] = "List regions !";
    ViewData["Menu"] = "Dealer";
}

<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading p-t-15 p-b-15">
                <a class="btn btn-primary waves-effect waves-light w-sm" asp-controller="Regions" asp-action="Create">
                    <span class="btn-label">
                        <i class="ion-plus-round"></i>
                    </span>
                    Add region
                </a>
            </div>
        </div>
    </div>
</div>

@foreach (var region in Model)
{
    <div class="row">
        <div class="col-xs-12">
            <div class="portlet">
                <div class="portlet-heading portlet-default">
                    <h3 class="portlet-title text-dark">
                        @region.Name
                    </h3>
                    <div class="portlet-widgets">
                        <a data-toggle="collapse" data-parent="#accordion1" href="#@region.Id" class="collapsed" aria-expanded="false"><i class="ion-minus-round"></i></a>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div id="@region.Id" class="panel-collapse collapse" aria-expanded="true">
                    <div class="panel-heading p-t-15 p-b-15">
                        <a class="btn btn-primary waves-effect waves-light w-sm" asp-controller="City" asp-action="Create" asp-route-regionId="@region.Id">
                            <span class="btn-label">
                                <i class="ion-plus-round"></i>
                            </span>
                            Add city
                        </a>
                        <div class="pull-right">
                            <a asp-controller="Regions" asp-action="Edit" asp-route-id="@region.Id" type="button" class="btn btn-success waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                                <i class="ion-edit"></i>
                            </a>
                            <form asp-controller="Regions" asp-action="Delete" method="post" style="display: inline-block" class="m-l-10">
                                <input type="hidden" value="@region.Id" name="id"/>
                                <button type="submit" class="btn btn-danger waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete">
                                    <i class="ion-trash-b"></i>
                                </button>
                            </form>
                        </div>
                    </div>

                    @if (region.Cities.Count > 0)
                    {
                        <div class="portlet-body">
                            <ul class="list-group">

                                @foreach (var city in region.Cities)
                                {
                                    <li class="list-group-item clearfix">
                                        <span class="m-t-5" style="display: inline-block">@city.Name</span> 

                                        <div class="pull-right">
                                            <a asp-controller="City" asp-action="Edit" asp-route-id="@city.Id" type="button" class="btn btn-success waves-effect waves-light btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit">
                                                <i class="ion-edit"></i>
                                            </a>
                                            <form asp-controller="City" asp-action="Delete" method="post" style="display: inline-block" class="m-l-10">
                                                <input type="hidden" value="@city.Id" name="id"/>
                                                <button type="submit" class="btn btn-danger waves-effect waves-light btn-sm" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete">
                                                    <i class="ion-trash-b"></i>
                                                </button>
                                            </form>
                                        </div>

                                    </li>
                                }

                            </ul>
                        </div>
                    }
                    
                </div>
            </div>
            
        </div>
    </div>
}