src/Pride2/Areas/Admin/ViewModels/ProductConfigurationItemViewModel.cs
using Pride2.Models;

namespace Pride2.Areas.Admin.ViewModels
{
    public class ProductConfigurationItemViewModel
    {
        public ProductConfigurationItem ProductConfigurationItem{ get; set; }
        public int ConfigurationId { get; set; }
    }
}

src/Pride2/Models/ProductConfigurationItem.cs
using System.ComponentModel.DataAnnotations;

namespace Pride2.Models
{
    public class ProductConfigurationItem
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        public virtual ProductConfiguration ProductConfiguration { get; set; }
        public virtual Stock Stock { get; set; }
    }
}

src/Pride2/Areas/Admin/Controllers/ProductConfigurationItemController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Pride2.Areas.Admin.ViewModels;
using Pride2.Models;

namespace Pride2.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admin/product/configuration/item")]
    public class ProductConfigurationItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductConfigurationItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("create")]
        public async Task<IActionResult> Create(int? configurationId)
        {
            if (configurationId != null)
            {
                var property = await _context.ProductConfigurations.FirstOrDefaultAsync(x => x.Id == configurationId.Value);

                if (property != null)
                {
                    ProductConfigurationItemViewModel model = new ProductConfigurationItemViewModel()
                    {
                        ProductConfigurationItem = new ProductConfigurationItem(),
                        ConfigurationId = configurationId.Value
                    };

                    return View("Edit", model);
                }
            }

            return HttpNotFound();
        }

        [Route("edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            ProductConfigurationItem configurationItem = await _context.ProductConfigurationItems.Include(x => x.ProductConfiguration).SingleAsync(x => x.Id == id);

            if (configurationItem != null)
            {
                ProductConfigurationItemViewModel model = new ProductConfigurationItemViewModel()
                {
                    ProductConfigurationItem = configurationItem,
                    ConfigurationId = configurationItem.ProductConfiguration.Id
                };

                return View(model);
            }

            return HttpNotFound();
        }

        [HttpPost("edit")]
        public async Task<IActionResult> Edit(ProductConfigurationItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.ProductConfigurationItem.ProductConfiguration = await _context.ProductConfigurations
                    .Include(x => x.Product)
                    .SingleOrDefaultAsync(x => x.Id == model.ConfigurationId);

                if (model.ProductConfigurationItem.ProductConfiguration == null)
                {
                    return HttpNotFound();
                }

                if (model.ProductConfigurationItem.Id == 0)
                {
                    _context.Entry(model.ProductConfigurationItem).State = EntityState.Added;

                    TempData["Message"] = $"Property item: {model.ProductConfigurationItem.Name} create!";
                }
                else
                {
                    _context.Entry(model.ProductConfigurationItem).State = EntityState.Modified;

                    TempData["Message"] = $"Property item: {model.ProductConfigurationItem.Name} save!";
                }

                await _context.SaveChangesAsync();

                return RedirectToAction("Edit", "Product", new { id = model.ProductConfigurationItem.ProductConfiguration.Product.Id });
            }

            return View(model);
        }

        [HttpPost("delete")]
        public async Task<IActionResult> Delete(int id)
        {
            ProductConfigurationItem configurationItem = await _context.ProductConfigurationItems
                .Include(x => x.ProductConfiguration)
                .ThenInclude(x => x.Product)
                .SingleAsync(x => x.Id == id);

            if (configurationItem != null)
            {
                _context.ProductConfigurationItems.Remove(configurationItem);

                TempData["Message"] = $"Property item: {configurationItem.Name} delete!";

                await _context.SaveChangesAsync();

                return RedirectToAction("Edit", "Product", new { configurationItem.ProductConfiguration.Product.Id });
            }

            return HttpNotFound();
        }
    }
}

src/Pride2/Areas/Admin/Views/ProductConfigurationItem/Edit.cshtml
@model Pride2.Areas.Admin.ViewModels.ProductConfigurationItemViewModel
@{
    ViewData["Title"] = "Configuration item edit";
    ViewData["Menu"] = "";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card-box">
            <div class="row">
                <div class="col-md-12">
                    <form class="form-horizontal" role="form" asp-controller="ProductConfigurationItem" asp-action="Edit" method="post">
                        <input type="hidden" asp-for="ProductConfigurationItem.Id" />
                        <input type="hidden" asp-for="ConfigurationId" />

                        <div class="form-group">
                            <div class="row">
                                <label class="col-md-2 control-label" asp-for="ProductConfigurationItem.Name"></label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" asp-for="ProductConfigurationItem.Name">
                                    <span class="error" asp-validation-for="ProductConfigurationItem.Name"></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group text-right m-b-0">
                            <button type="submit" class="btn btn-default">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}